version: '3.8'
services:
  books:
    build:
      context: ./books
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    depends_on:
      - mongo

  members:
    build:
      context: ./members
      dockerfile: Dockerfile
    ports:
      - '3002:3000'
    depends_on:
      - mongo

  loans:
    build:
      context: ./loans
      dockerfile: Dockerfile
    ports:
      - '3003:3000'
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - '27017:27017'

networks:
  default:
    driver: bridge